### ISSUE TITLE
[Feature] To-do-list

### ISSUE THREAD

**Issue by hansputera** [hansputera/gampang#1]
## Session Manager
- [x] `.auth` for authentication state, `.save()` to save current state, `.remove()` to removes current session folder/file.

## Safe Session Manager
- [x] File-as-session support (old authentication method)
- [x] SQL, and Non-SQL Database as session stores support, like (PostgreSQL, MySQL, MongoDB, and SQLite3)

## Bot
- [x] ~~Emit unhandled events on baileys to the `raw` event.~~ (we need to edit baileys source code)
- [x] Custom middleware
- [x] Add customizable cooldown middleware

cc: @QUERY-GANI

**Comment by hansputera** [comment]
Testing time...

**Comment by hansputera** [comment]
Logger issue
![image](https://user-images.githubusercontent.com/47862061/196025860-7d6cd4c3-0475-46ae-ad1d-03bab9e669e3.png)

**Comment by hansputera** [comment]
done
